#!/usr/local/bin/lci
HAI 10.5
IM IN YR woop UPPIN YR i TIL BOTH SAEM i AN 101
BOTH SAEM i AN 0, O RLY?
	YA RLY
	MEBBE NOT MOD OF i AN 15, VISIBLE "FizzBuzz"!
	MEBBE NOT MOD OF i AN 5, VISIBLE "Buzz"!
	MEBBE NOT MOD OF i AN 3, VISIBLE "Fizz"!
	NO WAI, VISIBLE i!
OIC
BOTH SAEM i AN 0, O RLY?
	YA RLY
	MEBBE BOTH SAEM i AN 100, VISIBLE ""
	NO WAI, VISIBLE " "!
OIC
IM OUTTA YR woop
KTHXBYE
